[pytest]
filterwarnings =
    ignore::UserWarning
    ignore:overflow encountered in expm1:RuntimeWarning:astropy.units.quantity
    ignore:invalid value encountered in divide:RuntimeWarning:astropy.units.quantity
    ignore:divide by zero encountered in divide:RuntimeWarning:astropy.units.quantity